# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelpcliAT0013 < Formula
  desc "The helpcli tool helps developers work efficiently in the terminal."
  homepage "https://github.com/heechankim/helpcli"
  version "0.0.13"
  license "mit"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.13/helpcli_Darwin_arm64.tar.gz"
      sha256 "78be23522fe0b1f11ed13b5b1b435a50155ac7828212b0f73ae87e47aa36a72f"

      def install
        bin.install "help"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.13/helpcli_Darwin_x86_64.tar.gz"
      sha256 "be62fb91bd578082fb204563d8929a891388edc18d170d246295e19e1e74e735"

      def install
        bin.install "help"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.13/helpcli_Linux_x86_64.tar.gz"
      sha256 "bf5813043730f43455cc514ba8b2a352012e94438a29d494a542ea0fd3441f83"

      def install
        bin.install "help"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.13/helpcli_Linux_arm64.tar.gz"
      sha256 "c6943d803e2da28c2642b21c4485b8e5cb77a544c7c358721739ddd1f0c28674"

      def install
        bin.install "help"
      end
    end
  end
end
